version: '3.8'
services:
  postgres:
    image: postgres
    container_name: postgres
    command: -N 1000
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: newsletter
      POSTGRES_PORT: 5432
    ports:
      - '5432:5432'
    networks:
      - zero2prod-network
  redis:
    image: redis:7
    container_name: redis
    ports:
      - '6379:6379'
    networks:
      - zero2prod-network
networks:
  zero2prod-network:
    driver: bridge